#file = open("filename","mode")
#file.close()

#while open("index.txt","r"): 
  
# file = open("index.txt",'a')
# content=file.read()
# print(content)

# file.close()
# while open("index.txt","a"):
#      f.write["Hello world how are you !\n"]
#      lines =["lines1\nlines2\nlines3\n"]
#      f.writelines(lines)

# import os
# if os .path.exists("index.txt"):
#      print("file exists") 
# else:
#      print("file does not exist") 

# import os
# os.mkdir("Mufakose")

# os.rmdir("mufakose")



