# boolean => it returns true or false

# print(10>5)
# print(7<=7)

# list are collection of items

# fruits = ("apple","banana","cherry","orange")
# numbers =(10,20,30,40,50)
# mixed_list =(True,1,2,0,"same",{1,2,3,})

# print(fruits)
# print(numbers)
# print(mixed_list)

# Accessing items in alist
# indexing => we use a postive  inde and a negative idex to access items in list
# positive index =>starts from 0 this is the first item

# fruits = ("apple"",banana","orange")
# print(fruits[0])
# print(fruits[-1])

# lisst slicing
# list{started:ending}

# numbers=[10,20,30,40,50]
# numbers[0]=5
# print(numbers)

# adding items 
# append and

# fruits =["apple","banana","orange"]
# fruits.pop()
# print (fruits)
# fruits.clear
# print(fruits)

# fruits.remove("banana")
# print(fruits)

# fruits.append(5)
# print(fruits)

# nums = [1,2,3,4,5,6,7,8,9,10]
# print(nums)
# nums.insert(4,5)


# print(nums)
# nums[-1] = 13
# print(nums)

# dictnaries

# student = {
# "name" : "memory",
# "age" : 20,
# "grade" : 8 ,
# "isAdult" : False}

# modify

# student["name"] = "Decent"










